### ISSUE TITLE
IFC Version NOT required 

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS-Audit-tool#1]
**Note**: moved here from https://github.com/CBenghi/ids-tool/issues/1 by @cicciopage

The tool requires that "ifcVersion" attribute inside "Specification" node is mandatory.
According to XSD, the "ifcVersion" attribute must be present but it could be empty.
Example:

1)
```
<ids:specification ifcVersion=""
		                   name="Spec 1"
		                   minOccurs="1"
		                   maxOccurs="1">
	<ids:applicability/>
	<ids:requirements/>
</ids:specification>
```

2)
```
<ids:specification ifcVersion="IFC2X3 IFC4 IFC4X3"
		                 name="Spec 2"
		                 minOccurs="1"
		                 maxOccurs="unbounded">
	<ids:applicability/>
	<ids:requirements/>
</ids:specification>
```

XSD:
```
<xs:attribute name="ifcVersion" use="required">
	<xs:simpleType>
		<xs:list>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="IFC2X3"/>
					<xs:enumeration value="IFC4"/>
					<xs:enumeration value="IFC4X3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:list>
	</xs:simpleType>
</xs:attribute>
```

**Comment by CBenghi** [comment]
Thanks @cicciopage,

I'm actually not sure how I would interpret the empty string.

I see two options: 

- no schema is acceptable (in which case the error is justified).
- all schemas are acceptable, but then why not list them all?

What would you do? I think this conversation needs to be had on the main IDS schema repository.

Best,
Claudio

**Comment by cicciopage** [comment]
XSD Schema is quite clear: IFCVersion attribute is required but it can be an empty string. One way to resolve the problem, that I can suggest, is if IFCVersion is empty not return an error but manage the file like if IFCVersion value is all available IFC versions.

**Comment by CBenghi** [comment]
I agree, but I think this needs to be a conversation on the main repository for IDS.

**Comment by cicciopage** [comment]
Ok, I think it's better we move the conversation on main repository, but I don't know how.

**Comment by CBenghi** [comment]
Just [open a new issue there IDS](https://github.com/buildingSMART/IDS/issues/new)

**Comment by cicciopage** [comment]
moved here:
[https://github.com/buildingSMART/IDS/issues/160](url)
