### ISSUE TITLE
Attribute cardinality check

### ISSUE THREAD

**Issue by ciroraggio** [buildingSMART/IDS-Audit-tool#10]
Hi,

validating an ids file containing this requirement:
```
<requirements>
      <attribute minOccurs="1" maxOccurs="unbounded">
           <name>
                <simpleValue>Name</simpleValue>
           </name>
      </attribute>
</requirements>
```
the validator returns these unexpected errors:
- _Error 306: Schema compliance error on "attribute at line 16, position 28"; "The 'minOccurs' attribute is not declared."_

- _Error 306: Schema compliance error on "attribute at line 16, position 42"; "The 'maxOccurs' attribute is not declared."_

I suppose it is due to this issue: https://github.com/buildingSMART/IDS/issues/144.
Would it be possible to reintroduce cardinality on attributes until the case is closed?

**Comment by CBenghi** [comment]
Done in a previous commit ahead of bS Lillestrøm 2023.
