### ISSUE TITLE
Positional Identifier value

### ISSUE THREAD

**Issue by francescoaielloALMA** [buildingSMART/IDS-Audit-tool#14]
Trying to validate the attached file, I get the following "PositionalIdentifier" values inside NodeIdentification objects. 

- /ids1/specifications1/specification2/applicability1/attribute1/name1/ids1/specifications1/specification2/applicability1/attribute1/name1/restriction1
- /ids1/specifications1/specification2/ids1/specifications1/specification2/applicability1
- /ids1/specifications1/ids1/specifications1/specification6

It looks like an unwanted repetition. How I should interprate them?

[ids file test.zip](https://github.com/buildingSMART/IDS-Audit-tool/files/12781764/ids.file.test.zip)

**Comment by CBenghi** [comment]
Thanks for the bug report. Fixed in [ce816ee](https://github.com/buildingSMART/IDS-Audit-tool/commit/ce816ee92b118dab89fc695efcfb8efeccc43dbe)
