### ISSUE TITLE
Test case "fail-patterns_only_work_on_strings_and_nothing_else.ids"

### ISSUE THREAD

**Issue by giuseppeverduciALMA** [buildingSMART/IDS-Audit-tool#15]
This test case:

https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-restriction.md#fail-patterns-only-work-on-strings-and-nothing-else

checks the consistency between the attribute type (IfcReal) and the use of pattern (restriction)

IDS-Audit-tool does not report this error, but it might be useful to report it

**Comment by CBenghi** [comment]
This makes sense. 

I think we are going in the direction of forbidding the use of `xs:types` because they are redundant (we have `datatype` for properties and the types of attributes are known from the schema).

Once that is settled I will come back and implement this feature.

**Comment by giuseppeverduciALMA** [comment]
Yes it is redundant.
I checked whether it is possible to avoid the 'base' attribute of 'restriction', but it seems to be mandatory: 
https://www.w3schools.com/xml/el_restriction.asp

**Comment by CBenghi** [comment]
Sadly, you seem to be right, I've looked at the official schema and it reads like this:

```xml
<xs:complexType name="restrictionType">
  <xs:complexContent>
    <xs:extension base="xs:annotated">
      <xs:sequence>
        <xs:choice minOccurs="0">
          <xs:group ref="xs:typeDefParticle"/>
          <xs:group ref="xs:simpleRestrictionModel"/>
        </xs:choice>
        <xs:group ref="xs:attrDecls"/>
      </xs:sequence>
      <xs:attribute name="base" type="xs:QName" use="required"/>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

Let's have a conversation about this in the IDS call. We might have to define a canonical match for each of the IFC datatypes.

**Comment by CBenghi** [comment]
Closing because a more explicit issue exists #27
