### ISSUE TITLE
Symbol for decimal number

### ISSUE THREAD

**Issue by CBenghi** [buildingSMART/IDS-Audit-tool#2]
**Note**: moved here from https://github.com/CBenghi/ids-tool/issues/2, initially submitted by @cicciopage

According to XSD, decimal number must have dot (.) symbol to separate the whole number from its fractional parts.
If the symbol is comma `,` as it's used in some locales, the tool must return an error.

Example:
Correct: 

```
12.3 
45.45 
67.444
```

Error:

``` 
12,3 
45,45 
67,444
```

**Comment by CBenghi** [comment]
Thanks @cicciopage,

this makes sense, but I wonder how we can implement it.

Commas are not inherently a problem. This would probably apply to the value of properties that 
- have an IFC measure, or 
- are one of the default properties with predefined numeric type.

Can you think of other scenarios?

**Comment by cicciopage** [comment]
Yes, I speak about values inside the restrictions, where we have also the type (xs:decimal).

**Comment by CBenghi** [comment]
> Yes, I speak about values inside the restrictions, where we have also the type (xs:decimal).

This makes total sense. I'll implement it.

**Comment by CBenghi** [comment]
This is also on hold as we define what to do with regards to the `xs` restriction types (they might be redundant).

**Comment by CBenghi** [comment]
I think this has been implemented quite some time ago, but I forgot to close the issue.
