### ISSUE TITLE
Regular Expression Values Exception

### ISSUE THREAD

**Issue by francescoaielloALMA** [buildingSMART/IDS-Audit-tool#22]
Hi! I'm getting exception when I try to validate IDS file that contains regular expression with escape chars inside (for instance:  "\d").
The exception is: "Invalid pattern...".
In the attachements there is a sample file.

[reg_exp_error.zip](https://github.com/buildingSMART/IDS-Audit-tool/files/13701676/reg_exp_error.zip)

**Comment by aothms** [comment]
> `<xs:pattern value="CUP\d{8}"/>`

I think `\d` is not allowed in XSD regex flavour. Did you try `CUP[0-9]{8}`?

https://www.w3.org/TR/xmlschema11-2/#regex-piece

**Comment by francescoaielloALMA** [comment]
I don't know, but I think that Audit Tool must catch the exception and put it in the validation errors list.
Actually the tool crashes.

**Comment by francescoaielloALMA** [comment]
Any news about this issue? Thanks

**Comment by francescoaielloALMA** [comment]
I found the issue. The problem was in my code. The issue can be closed.
