### ISSUE TITLE
Solution dependencies - Code Generator depends on Tests project

### ISSUE THREAD

**Issue by andyward** [buildingSMART/IDS-Audit-tool#24]
Internal technical issue spotted when doing PR #23 - the **ids-lib.codgen** project depends on the **ids-tools.tests** so it can re-use the code to get some buildingSmart files using the [BuildingSmartRepoFiles Helper](https://github.com/buildingSMART/IDS-Audit-tool/blob/main/ids-tool.tests/Helpers/BuildingSmartRepoFiles.cs)

Obviously it works but it does seem a little quirky since it creates a circular loop.  e.g. If you were regenerate broken code, (or removed the generated code) you'd not be able to build to code-generator to regenerate new code. I'd expect the code generator to have no internal dependencies and be at the 'bottom' of the stack of projects.

Perhaps that helper should be factored out to a common library, or maybe just a shared file so the dependency can be broken. Alternatively, we should move the helper to codegen. Can do a PR if you like

**Comment by CBenghi** [comment]
@andyward,
agreed I cut corners there a bit. I think I can live with that, but if you want to invest time fixing, a PR is welcome.

**Comment by CBenghi** [comment]
Hi @andyward,
I had a few minutes and fixed this with the shared SolutionTooling library.
