### ISSUE TITLE
Pset_ConstructionOccurence ifc4x3 miss in audit-tool validation 

### ISSUE THREAD

**Issue by stefaniafrattoALMA** [buildingSMART/IDS-Audit-tool#25]
Hi, 
I was creating a new IDS file, according to some clients specifications, and when i try to validate it with Audit-tool validator, i receive many errors with this signature "Reserved prefix 'Pset_' for property set name (Pset_ConstructionOccurence) in the context of Ifc4x3 on 'property', but i found this Pset in documentation [https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_ConstructionOccurence.htm](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_ConstructionOccurence.htm)

Thanks

**Comment by CBenghi** [comment]
@andyward,
The list is generated from xbim.properties metadata, is there an update available that includes the release version of 4x3?

**Comment by CBenghi** [comment]
@stefaniafrattoALMA,
can you upload an IDS to add to the test suite, so that I can reproduce?

**Comment by andyward** [comment]
> @andyward, The list is generated from xbim.properties metadata, is there an update available that includes the release version of 4x3?
 
It was updated a while back https://github.com/xBimTeam/XbimPropertySets/commit/12085311209bcbab90ff0a6ef2c11ed62e45d3c0#diff-ddb3255c6f27c81feacfb10f331aa76cf41b6523c07038c2a5aed43354bedaa2

Just had a quick check and it seems to have had a package rename between v4 and v6 (accidentally I expect). So it's available as _xbim.Properties_ v6.0.10 in myget (nuget soon - I just pushed it). Previously it was _xbim.PropertySets_ v4.0.1 (without ifc4x3 support). Will follow up if we can unify the package names

**Comment by CBenghi** [comment]
@andyward,
there's a little discrepancy on that propertySet name... `Pset_ConstructionOccurance` vs `Pset_ConstructionOccurence`!
That's strange.

**Comment by andyward** [comment]
> @andyward, there's a little discrepancy on that propertySet name... `Pset_ConstructionOccurance` vs `Pset_ConstructionOccurence`! That's strange.

I think we just took the content from https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/annex-a.html (last link). That seems correct now

Looks like at some point it's been renamed to fix the typo, but we must have picked up an earlier version. https://github.com/buildingSMART/IFC4.3.x-development/commit/a51218022498e430e7e0f9e8e1d928819a860a4f

Do you want me to re-publish xbim.Properties?

**Comment by andyward** [comment]
6.0.11 of xbim.Properties should fix this. We'd not updated the Psets since IFC4X3_ADD2 was released.

BTW, assuming the issue title is wrong? There is no Pset_**Concrete**Occurence

Final note: despite the typo correction I think Occurrence is still mis-spelt in the standard. It should be double-R in Occur**r**ence . I had to look it up as I thought it still looked wrong.

**Comment by CBenghi** [comment]
Hi @andyward,
Excellent, I'll update the reference soon.
This makes me think how potentially difficult the management of the versioning would be in the long term for IDS.
But we'll cross that bridge when we get there.
Many thanks,
Claudio

**Comment by CBenghi** [comment]
@stefaniafrattoALMA I've had to rename the PsetName in the file, cause it was not quite right:
The pset spelling from the documentation should be `Pset_ConstructionOccurence` (it's missing an r).

see 4df7222c5d999ecbd996517f80a3c2ca0669692a
