### ISSUE TITLE
Possible bug in GetConcreteClassesFrom method

### ISSUE THREAD

**Issue by IbrahimFahdah** [buildingSMART/IDS-Audit-tool#34]
When using a single IfcSchemaVersion, the passed value is ignored and the first value in IfcSchemaVersions.IfcAllVersions is used.  Is this a bug?

 public static IEnumerable<string> GetConcreteClassesFrom(string topClass, IfcSchemaVersions schemaVersions)
 {
     if (schemaVersions.IsSingleSchema())
     {
         **SchemaInfo schemaInfo = GetSchemas(IfcSchemaVersions.IfcAllVersions).First();**
.....
     }

   .....
 }

**Comment by CBenghi** [comment]
I think you're right. I'll have a better look.
