### ISSUE TITLE
Need to update for correct IFC4X3 identifier in IDS1.0

### ISSUE THREAD

**Issue by andyward** [buildingSMART/IDS-Audit-tool#35]
_IfcSchemaVersionsExtensions.cs_ still refers to "IFC4X3" rather than "IFC4X3_ADD2", meaning any consumers like XIDS output invalid ifcVersions when using 4x3

**Comment by CBenghi** [comment]
Addressed in https://github.com/buildingSMART/IDS-Audit-tool/commit/620402ec011bd36e9c90b0784a531832e25d88e6
